# PHP CircleCI 2.0 configuration file# PHP CircleCI 2 
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1.5-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}       
      - run: 
          name: "Testes"
          command: vendor/phpunit/phpunit/phpunit Teste
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: ssh lucas-tomasi@138.68.174.210 "dep deploy"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master