# PHP CircleCI 2.0 configuration file# PHP CircleCI 2 
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.5-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
        
      # run tests!
      - run: 
          name: "Testes"
          command: vendor/phpunit/phpunit/phpunit Teste
      - run: 
          name: "Install Deploy"
          command: curl -LO https://deployer.org/deployer.phar ; chmod +x deployer.phar;
      - add_ssh_keys:
          fingerprints:
            - "e4:6c:d3:e4:d5:1c:ca:39:26:2b:ec:9a:21:dd:74:4c"
      - run:
          name: "SSH Config"
          command: echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBW752OOZ3sC27p9kHXXJF1pCVjrs80XAnwKovOt/YcS8pInVDZcGJ9SAC3b7MVXWaHYgQKHg1XOmCuGTJ9XAWkLB30tcfdMDniHRrq/0oAE9fjESgJxYugaxT4+t1RP/rs2sQ5UD4qS3A//Unq1jERM/7SA+msHx91FRTjbZzmI51pfc1/nbB6M87FAQ/hrSn7pLnCZ8ntII+mLrrTVuh282xe1mkNkE7ThHxPQ7FdVvKD4LDBXKEz/WEvRbZD4uBwsEaoCEPqniu7mx0/vbdongxSr44jWybexaQh8+m+C27IExVmcVsNQwUFPliYX2gWKlzExm0UxCX3esYuTdn lucas-tomasi@lucas-deploy" >> ~/.ssh/known_hosts
      - run:
          name: "Deploy"
          command: ./deployer.phar deploy
