version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-apache-stretch-node-browsers
    steps:
      - checkout
    run:
      - composer install
  test:
    run:
      - vendor/phpunit/phpunit/phpunit Teste
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
