version: 3
jobs:
  build_and_test:
    docker:
      - image: circleci/php:7.2-apache-stretch-node-browsers
    steps:
      - checkout
      - run:  composer install
      - run:  vendor/phpunit/phpunit/phpunit Teste